version: "3.7"

services:
  frontend:
    depends_on:
      - backend
      - auth
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env
  backend:
    depends_on:
      - mysql
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - ./backend/.env

  auth:
    depends_on:
      - mongodb
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - 3331:3331
    env_file:
      - ./auth/.env

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

volumes:
  my-db:
  mongodata:
