version: "3.7"

services:
  frontend:
    depends_on:
      - backend
      - auth
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env.prod
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  backend:
    depends_on:
      mysql:
        condition: service_started 
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - ./backend/.env.prod
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  auth:
    depends_on:
      - mongodb
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - 3331:3331
    env_file:
      - ./auth/.env.prod
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  mysql:
    image: mysql:5.7
    container_name: mysql
    env_file:
      - ./.env.prod
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    # healthcheck:
    #   test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    #   timeout: 20s
    #   retries: 10

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
volumes:
  my-db:
  mongodata:
  
